site_name: OKCzero's Notes

repo_url: https://github.com/ok-zero/Notes
repo_name: OK-zero/Notes
# edit_uri: edit/main/docs # edit link to the GitHub repository

theme:
  name: material
  custom_dir: overrides
  features:
    # Set for build-in search
    - search.suggest
    - search.highlight
    - search.share
    # Include file to nav
    - include_dir_to_nav:
      sort_file: true
      sort_directory: true
    # Set for navigation
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    # - header.autohide
    # - toc.integrate
    # Set for Code
    - content.code.copy
    - content.code.select
    - content.code.annotate

  icon:
    # logo: bootstrap/envelope-paper
    repo: fontawesome/brands/github
    edit: material/pencil # edit button icon

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  # palette:
  #   # Palette toggle for dark mode
  #   - scheme: slate
  #     primary: black
  #     toggle:
  #       icon: material/brightness-4
  #       name: Switch to light mode
  #   # Palette toggle for light mode
  #   - scheme: default
  #     primary: white
  #     toggle:
  #       icon: material/brightness-7
  #       name: Switch to auto mode
  #   # Palette toggle for auto mode
  #   - scheme: auto
  #     toggle:
  #       icon: material/brightness-auto
  #       name: Switch to dark mode

  font:
    text: Roboto
    code: Fira Code

nav:
  - Home: index.md
  - Tags: tags.md
  - Test: test.md
  - 微积分:
      - Home: Calculus/index.md
      - 定理:
          - 达布定理: Calculus/theorem/达布定理.md
          - 沃利斯公式: Calculus/theorem/沃利斯公式.md
          - Stirling公式: Calculus/theorem/Stirling公式.md
    # - 级数: Calculus/级数.md

copyright: Copyright &copy; 2024 OKCzero

markdown_extensions:
  - abbr
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde

  # - Support for Markdown Syntax Extra
  # -----------------------------------
  # Support for markdown tables
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

  # Generate permalink anchors for headings
  - toc:
      permalink: true
      permalink_class: toc-anchor
      # permalink_symbol: ¶

  # Support for aligning images, adding captions to images (rendering them as figures), and marking large images for lazy-loading
  - attr_list
  - md_in_html

  # Support for LaTeX math
  - pymdownx.arithmatex:
      generic: true
  # Support for code syntax highlighting
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.highlight:
      use_pygments: true
      guess_lang: true
      auto_title: true
      # pygments_lang_class: true
      linenums: true
      linenums_style: "table"
      anchor_linenums: true
      line_spans: __span

  # Support for extra Markdown syntax
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

  # Support for Markdown
  - meta

  # - Support for emoji
  # -------------------
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons

extra_javascript:
  # Support for LaTeX math using MathJax
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  # Support
  - css/styles.css

extra:
  # Set the language of the website
  # alternate:
  #   - name: English
  #     link: /en/
  #     lang: en
  #   - name: Chinese
  #     link: /zh/
  #     lang: zh
  # Delete 'Made with Material for MkDocs' in the footer
  # generator: false
  # Set website analytics
  analytics:
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.

    provider: google
    property: G-5HK4NWGSB9
  # Set the contact favicon
  social:
    # - icon: fontawesome/brands/twitter
    #   link: https://twitter.com/wcowin_
    - icon: fontawesome/brands/github
      link: https://github.com/OK-zero
    # - icon: fontawesome/brands/bilibili
    #   link:
    - icon: bootstrap/envelope
      link: mailto:<okczero@outlook.com> #联系方式

# disqus: true

plugins:
  # - meta
  # Support for build-in search
  - search:
      lang:
        - en
        - zh
      jieba_dict: dict.txt
      separator: '[\s\u200b\-]'
  # Support for zooming in on images
  - glightbox

  - tags:
      tags_file: tags.md
      # enabled: !ENV [CI, false]

  - git-revision-date-localized:
      enable_creation_date: true

  - blog:
      # post_readtime: true
